[ERROR  ] UI Automation encountered an error
Traceback (most recent call last):
  File "C:\Users\batam\DOCUME~1\GLEEMA~2\GLEEMA~1\Modules\03_Window\007_ui_automation\main.py", line 341, in run
  File "C:\Users\batam\DOCUME~1\GLEEMA~2\GLEEMA~1\subprocess.py", line 356, in check_output
  File "C:\Users\batam\DOCUME~1\GLEEMA~2\GLEEMA~1\subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['python', 'C:\\Users\\batam\\DOCUME~1\\GLEEMA~2\\GLEEMA~1\\packages\\uiautomation\\uia.py', '{"target_element": "icons\\\\2025_07_21_15_36_40_456320cropped_icon.png", "parent_element": ["PT Jasa Armada Indonesia Tbk (IPCM.JK) Stock Price, News, Quote & History - Yahoo Finance - Google Chrome - PNM UI", "Chrome_WidgetWin_1", "Pane", ["PT Jasa Armada Indonesia Tbk (IPCM.JK) Stock Price, News, Quote & History - Yahoo Finance - Google Chrome - PNM UI"], 4], "type": "Move"}']' returned non-zero exit status 1.